### ISSUE TITLE
Errors when used in own project

### ISSUE THREAD

**Issue by haydgately** [mohammad-rahchamani/MailView#1]
Hi! I have downloaded and built the demo app, it works great! 

I tried to install it via SPM but it failed, and when including it into my project I get quite a few errors, mainly 

Cannot specialize non-generic type 'Result'
Replace '<MailViewResult, Error>' with ''

Have you encountered this before? I don't seem to be able to get this to work in my own project by dragging it in or creating the same files. Thanks

**Comment by mohammad-rahchamani** [comment]
@haydgately  it would be nice if you provide more information for future reference. 
thanks.
