### ISSUE TITLE
Including in project

### ISSUE THREAD

**Issue by haydgately** [mohammad-rahchamani/MailView#2]
Hi, 

I can get the standalone project to work but when I copy the 3 files MailView.swift, MailView.h and info.plist, I get no such module found. 

SPM fails without a manifest, how would you incorporate this into another project? 

Cheers

**Comment by arbyruns** [comment]
You shouldn't need to move info.plist.  You should just need to move

- MailView.h
- MailView.swift
- Content from ContentView.swift
