### ISSUE TITLE
Sample of adding an attachment

### ISSUE THREAD

**Issue by TonyCat** [mohammad-rahchamani/MailView#3]
I've been trying to add an attachment to the email but am having some trouble can you update the example to show attaching a pdf?

**Comment by mohammad-rahchamani** [comment]
Sorry for my late answer. I've just updated the sample in c2c9bab0e5b376b0365835c609cb178bec57e084 with an attachment.
You just have to parse the file contents `Data` and set the Mime type to `application/pdf`.
