### ISSUE TITLE
SwiftUI Issue

### ISSUE THREAD

**Issue by tazmancoder** [mohammad-rahchamani/MailView#4]
When I include this in my SwiftUI project I get the following errors.

Here are the following errors I get:
1. @Binding is only available in iOS 13.0
2. 'setPreferredSendingEmailAddress' is only available in iOS 11.0 or newer
3. 'some' return types are only available in iOS 13.0.0 or newer
4. 'open(_:options:completionHandler:)' is only available in iOS 10.0 or newer
5. 'Group' is only available in iOS 13.0 or newer
6. 'EmptyView' is only available in iOS 13.0 or newer

If I go into the Swift Package and into MailView.swift and put the following code: @available(iOS 13.0, *). in a few places all the errors go away. Could you please fix this? I really like this MailView and want to use it as a Swift package.

**Comment by myanalysis** [comment]
I am having same errors.  I am on iOS 14.  Tried to downgrand to iOS 13 and no difference.

**Comment by mohammad-rahchamani** [comment]
@appledad05 @myanalysis sorry for my late answer. I've fixed the problem. You can use version `1.0.0` without any problems.
